# Mercedes-Benz Greener Manufacturing

## Project-01

In [1]:
# First Importing the required Library 
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 

In [2]:
# Importing the data set
benz_train_df = pd.read_csv("train.csv")

In [3]:
# Removing the warning
import warnings
warnings.filterwarnings("ignore")

In [4]:
benz_train_df.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

In [5]:
benz_train_df.shape

(4209, 378)

In [6]:
benz_train_df.info(verbose=True, null_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Data columns (total 378 columns):
 #    Column  Non-Null Count  Dtype  
---   ------  --------------  -----  
 0    ID      4209 non-null   int64  
 1    y       4209 non-null   float64
 2    X0      4209 non-null   object 
 3    X1      4209 non-null   object 
 4    X2      4209 non-null   object 
 5    X3      4209 non-null   object 
 6    X4      4209 non-null   object 
 7    X5      4209 non-null   object 
 8    X6      4209 non-null   object 
 9    X8      4209 non-null   object 
 10   X10     4209 non-null   int64  
 11   X11     4209 non-null   int64  
 12   X12     4209 non-null   int64  
 13   X13     4209 non-null   int64  
 14   X14     4209 non-null   int64  
 15   X15     4209 non-null   int64  
 16   X16     4209 non-null   int64  
 17   X17     4209 non-null   int64  
 18   X18     4209 non-null   int64  
 19   X19     4209 non-null   int64  
 20   X20     4209 non-null   int64  
 21   X21     4209

In [7]:
benz_train_df.describe()

ID            y          X10     X11          X12  \
count  4209.000000  4209.000000  4209.000000  4209.0  4209.000000   
mean   4205.960798   100.669318     0.013305     0.0     0.075077   
std    2437.608688    12.679381     0.114590     0.0     0.263547   
min       0.000000    72.110000     0.000000     0.0     0.000000   
25%    2095.000000    90.820000     0.000000     0.0     0.000000   
50%    4220.000000    99.150000     0.000000     0.0     0.000000   
75%    6314.000000   109.010000     0.000000     0.0     0.000000   
max    8417.000000   265.320000     1.000000     0.0     1.000000   

               X13          X14          X15          X16          X17  ...  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  ...   
mean      0.057971     0.428130     0.000475     0.002613     0.007603  ...   
std       0.233716     0.494867     0.021796     0.051061     0.086872  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       0.000000     1.000000     0.000000     0.000000     0.000000  ...   
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...   

              X375         X376         X377         X378         X379  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000   
mean      0.318841     0.057258     0.314802     0.020670     0.009503   
std       0.466082     0.232363     0.464492     0.142294     0.097033   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       1.000000     0.000000     1.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

              X380         X382         X383         X384         X385  
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  
mean      0.008078     0.007603     0.001663     0.000475     0.001426  
std       0.089524     0.086872     0.040752     0.021796     0.037734  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000     0.000000  
max       1.000000     1.000000     1.000000     1.000000     1.000000  

[8 rows x 370 columns]

### 1. removing those variable(s), In case of any column(s), the variance is equal to zero.

In [8]:
# First removing the Columns that is not in use 
benz_train_df.drop("ID", axis=1, inplace=True)

In [9]:
benz_train_df.var()

y       160.766710
X10       0.013131
X11       0.000000
X12       0.069457
X13       0.054623
           ...    
X380      0.008015
X382      0.007547
X383      0.001661
X384      0.000475
X385      0.001424
Length: 369, dtype: float64

In [10]:
Col_Zero_Var = benz_train_df.var()[benz_train_df.var()==0].index.values
Col_Zero_Var

array(['X11', 'X93', 'X107', 'X233', 'X235', 'X268', 'X289', 'X290',
       'X293', 'X297', 'X330', 'X347'], dtype=object)

In [11]:
benz_train_df = benz_train_df.drop(Col_Zero_Var, axis=1)

In [12]:
benz_train_df.head()

y  X0 X1  X2 X3 X4 X5 X6 X8  X10  ...  X375  X376  X377  X378  X379  \
0  130.81   k  v  at  a  d  u  j  o    0  ...     0     0     1     0     0   
1   88.53   k  t  av  e  d  y  l  o    0  ...     1     0     0     0     0   
2   76.26  az  w   n  c  d  x  j  x    0  ...     0     0     0     0     0   
3   80.62  az  t   n  f  d  x  l  e    0  ...     0     0     0     0     0   
4   78.02  az  v   n  f  d  h  d  n    0  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 365 columns]

### 2. Checking the null and unique values for train set.

In [13]:
# checking The number of null values
benz_train_df.isnull().sum().values

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [14]:
# Now Checking the Number of unique values in each rows 
pd.DataFrame(benz_train_df.nunique(), benz_train_df.nunique().index.values)

0
y     2545
X0      47
X1      27
X2      44
X3       7
...    ...
X380     2
X382     2
X383     2
X384     2
X385     2

[365 rows x 1 columns]

### 3. Appling the Label Encoder 

In [15]:
# Before appliyng the label encoder first need to check the object variables
benz_train_obj = benz_train_df.select_dtypes(include=object)
benz_train_obj

X0 X1  X2 X3 X4  X5 X6 X8
0      k  v  at  a  d   u  j  o
1      k  t  av  e  d   y  l  o
2     az  w   n  c  d   x  j  x
3     az  t   n  f  d   x  l  e
4     az  v   n  f  d   h  d  n
...   .. ..  .. .. ..  .. .. ..
4204  ak  s  as  c  d  aa  d  q
4205   j  o   t  d  d  aa  h  h
4206  ak  v   r  a  d  aa  g  e
4207  al  r   e  f  d  aa  l  u
4208   z  r  ae  c  d  aa  g  w

[4209 rows x 8 columns]

In [16]:
# Importing the label encoder 
from sklearn.preprocessing import LabelEncoder 
le = LabelEncoder()

In [17]:
benz_train_df["X0"] = le.fit_transform(benz_train_df["X0"])
benz_train_df["X1"] = le.fit_transform(benz_train_df["X1"])
benz_train_df["X2"] = le.fit_transform(benz_train_df["X2"])
benz_train_df["X3"] = le.fit_transform(benz_train_df["X3"])
benz_train_df["X4"] = le.fit_transform(benz_train_df["X4"])
benz_train_df["X5"] = le.fit_transform(benz_train_df["X5"])
benz_train_df["X6"] = le.fit_transform(benz_train_df["X6"])
benz_train_df["X8"] = le.fit_transform(benz_train_df["X8"])

In [18]:
benz_train_df["X0"]  # category has been converted into the num and datatype is int now.

0       32
1       32
2       20
3       20
4       20
        ..
4204     8
4205    31
4206     8
4207     9
4208    46
Name: X0, Length: 4209, dtype: int32

In [19]:
benz_train_df

y  X0  X1  X2  X3  X4  X5  X6  X8  X10  ...  X375  X376  X377  \
0     130.81  32  23  17   0   3  24   9  14    0  ...     0     0     1   
1      88.53  32  21  19   4   3  28  11  14    0  ...     1     0     0   
2      76.26  20  24  34   2   3  27   9  23    0  ...     0     0     0   
3      80.62  20  21  34   5   3  27  11   4    0  ...     0     0     0   
4      78.02  20  23  34   5   3  12   3  13    0  ...     0     0     0   
...      ...  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...   ...   ...   ...   
4204  107.39   8  20  16   2   3   0   3  16    0  ...     1     0     0   
4205  108.77  31  16  40   3   3   0   7   7    0  ...     0     1     0   
4206  109.22   8  23  38   0   3   0   6   4    0  ...     0     0     1   
4207   87.48   9  19  25   5   3   0  11  20    0  ...     0     0     0   
4208  110.85  46  19   3   2   3   0   6  22    0  ...     1     0     0   

      X378  X379  X380  X382  X383  X384  X385  
0        0     0     0     0     0     0     0  
1        0     0     0     0     0     0     0  
2        0     0     0     1     0     0     0  
3        0     0     0     0     0     0     0  
4        0     0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...   ...  
4204     0     0     0     0     0     0     0  
4205     0     0     0     0     0     0     0  
4206     0     0     0     0     0     0     0  
4207     0     0     0     0     0     0     0  
4208     0     0     0     0     0     0     0  

[4209 rows x 365 columns]

### 4. Performing Principal component analysis(PCA)

In [20]:
x_benz_train_df = benz_train_df.drop('y', axis=1)
y_benz_train_df = benz_train_df['y']

In [21]:
# Importing the PCA
from sklearn.decomposition import PCA
pca = PCA(n_components=25)

In [22]:
x_benz_train_df = pca.fit_transform(x_benz_train_df)

In [23]:
pca.explained_variance_ratio_

array([0.38334782, 0.21388033, 0.13261866, 0.11826642, 0.09206008,
       0.01590604, 0.0074454 , 0.00433701, 0.00294021, 0.00241796,
       0.00236488, 0.00203229, 0.00167204, 0.00148111, 0.00128702,
       0.00103575, 0.00095733, 0.00089696, 0.00078569, 0.00070972,
       0.00064438, 0.00062381, 0.00058461, 0.00051244, 0.00048478])

# Loading test set 

In [24]:
# First importing test set
benz_test_df = pd.read_csv("test.csv")

In [25]:
benz_test_df.head()

ID  X0 X1  X2 X3 X4 X5 X6 X8  X10  ...  X375  X376  X377  X378  X379  X380  \
0   1  az  v   n  f  d  t  a  w    0  ...     0     0     0     1     0     0   
1   2   t  b  ai  a  d  b  g  y    0  ...     0     0     1     0     0     0   
2   3  az  v  as  f  d  a  j  j    0  ...     0     0     0     1     0     0   
3   4  az  l   n  f  d  z  l  n    0  ...     0     0     0     1     0     0   
4   5   w  s  as  c  d  y  i  m    0  ...     1     0     0     0     0     0   

   X382  X383  X384  X385  
0     0     0     0     0  
1     0     0     0     0  
2     0     0     0     0  
3     0     0     0     0  
4     0     0     0     0  

[5 rows x 377 columns]

In [26]:
# First removing the Columns that is not in use 
benz_test_df.drop("ID", axis=1, inplace=True)

### 1. Test Dataset- Removing the variable with the zero Variance 

In [27]:
benz_test_df.var()

X10     0.018650
X11     0.000238
X12     0.068851
X13     0.057345
X14     0.244859
          ...   
X380    0.008015
X382    0.008715
X383    0.000475
X384    0.000712
X385    0.001661
Length: 368, dtype: float64

In [28]:
Cols_Zero_Var = benz_test_df.var()[benz_test_df.var()==0].index.values
Cols_Zero_Var

array(['X257', 'X258', 'X295', 'X296', 'X369'], dtype=object)

In [29]:
benz_test_df = benz_test_df.drop(Cols_Zero_Var, axis=1)

In [30]:
benz_test_df.head()

X0 X1  X2 X3 X4 X5 X6 X8  X10  X11  ...  X375  X376  X377  X378  X379  \
0  az  v   n  f  d  t  a  w    0    0  ...     0     0     0     1     0   
1   t  b  ai  a  d  b  g  y    0    0  ...     0     0     1     0     0   
2  az  v  as  f  d  a  j  j    0    0  ...     0     0     0     1     0   
3  az  l   n  f  d  z  l  n    0    0  ...     0     0     0     1     0   
4   w  s  as  c  d  y  i  m    0    0  ...     1     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     0     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 371 columns]

### 2. Test Dataset- Checking the null and unique values.

In [31]:
# checking The number of null values
benz_test_df.isnull().sum().values

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [32]:
# Now Checking the Number of unique values in each rows 
benz_test_df.nunique()

X0      49
X1      27
X2      45
X3       7
X4       4
        ..
X380     2
X382     2
X383     2
X384     2
X385     2
Length: 371, dtype: int64

### 3. Test Dataset- label Encoding 

In [33]:
# Before appliyng the label encoder first need to check the object variables
benz_test_obj = benz_test_df.select_dtypes(include=object)
benz_test_obj

X0  X1  X2 X3 X4  X5 X6 X8
0     az   v   n  f  d   t  a  w
1      t   b  ai  a  d   b  g  y
2     az   v  as  f  d   a  j  j
3     az   l   n  f  d   z  l  n
4      w   s  as  c  d   y  i  m
...   ..  ..  .. .. ..  .. .. ..
4204  aj   h  as  f  d  aa  j  e
4205   t  aa  ai  d  d  aa  j  y
4206   y   v  as  f  d  aa  d  w
4207  ak   v  as  a  d  aa  c  q
4208   t  aa  ai  c  d  aa  g  r

[4209 rows x 8 columns]

In [34]:
# Importing the label encoder 
from sklearn.preprocessing import LabelEncoder 
le = LabelEncoder()

In [35]:
benz_test_df["X0"] = le.fit_transform(benz_test_df["X0"])
benz_test_df["X1"] = le.fit_transform(benz_test_df["X1"])
benz_test_df["X2"] = le.fit_transform(benz_test_df["X2"])
benz_test_df["X3"] = le.fit_transform(benz_test_df["X3"])
benz_test_df["X4"] = le.fit_transform(benz_test_df["X4"])
benz_test_df["X5"] = le.fit_transform(benz_test_df["X5"])
benz_test_df["X6"] = le.fit_transform(benz_test_df["X6"])
benz_test_df["X8"] = le.fit_transform(benz_test_df["X8"])

In [36]:
benz_test_df.head()  # category has been converted into the num and datatype is int now.

X0  X1  X2  X3  X4  X5  X6  X8  X10  X11  ...  X375  X376  X377  X378  \
0  21  23  34   5   3  26   0  22    0    0  ...     0     0     0     1   
1  42   3   8   0   3   9   6  24    0    0  ...     0     0     1     0   
2  21  23  17   5   3   0   9   9    0    0  ...     0     0     0     1   
3  21  13  34   5   3  31  11  13    0    0  ...     0     0     0     1   
4  45  20  17   2   3  30   8  12    0    0  ...     1     0     0     0   

   X379  X380  X382  X383  X384  X385  
0     0     0     0     0     0     0  
1     0     0     0     0     0     0  
2     0     0     0     0     0     0  
3     0     0     0     0     0     0  
4     0     0     0     0     0     0  

[5 rows x 371 columns]

### 4. Test Data - Performing PCA

In [37]:
# Importing the PCA
from sklearn.decomposition import PCA
pca = PCA(n_components=25)

In [38]:
benz_test_df = pca.fit_transform(benz_test_df)

In [39]:
pca.explained_variance_ratio_

array([4.35151022e-01, 1.76708968e-01, 1.36462922e-01, 1.09779117e-01,
       8.62220781e-02, 1.43396216e-02, 7.22965696e-03, 4.06842812e-03,
       2.74007140e-03, 2.28112005e-03, 2.21525436e-03, 1.82720604e-03,
       1.58124816e-03, 1.38440129e-03, 1.20790398e-03, 9.97167275e-04,
       8.91795019e-04, 8.24607683e-04, 7.23297981e-04, 6.55857458e-04,
       6.23926459e-04, 5.77429002e-04, 5.42155436e-04, 4.91811480e-04,
       4.34729010e-04])

In [40]:
benz_test_df

array([[ 1.45833617e+01,  1.41667255e+01,  1.35385760e+01, ...,
        -4.61917555e-02, -4.96719091e-01, -1.94540551e-01],
       [-1.52516126e+01, -7.73675622e+00, -7.45495093e+00, ...,
         4.80851179e-01,  7.69800868e-01,  3.41165813e-01],
       [ 1.18564648e+01, -1.68017313e+00, -9.98961457e+00, ...,
        -1.08553174e+00,  1.03798573e+00, -4.81080149e-02],
       ...,
       [-1.34464401e+01,  3.28858211e+00, -6.85236379e+00, ...,
        -5.03410635e-02, -3.84377813e-01,  4.42183308e-01],
       [ 2.49261231e+01, -4.89888665e+00, -1.01694102e+01, ...,
        -1.83221522e-01,  2.19392188e-01,  1.07450120e+00],
       [-1.53843098e+01, -7.73425450e+00, -1.54930106e+01, ...,
         1.58647759e-01, -3.80663553e-01,  2.23984913e-02]])

### 5. Predicting test_data values using XGBoost.

In [41]:
from xgboost import XGBRegressor

In [45]:
xgb = XGBRegressor()
xgb.fit(x_benz_train_df,y_benz_train_df)

XGBRegressor(base_score=0.5, booster='gbtree', callbacks=None,
             colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
             early_stopping_rounds=None, enable_categorical=False,
             eval_metric=None, feature_types=None, gamma=0, gpu_id=-1,
             grow_policy='depthwise', importance_type=None,
             interaction_constraints='', learning_rate=0.300000012, max_bin=256,
             max_cat_threshold=64, max_cat_to_onehot=4, max_delta_step=0,
             max_depth=6, max_leaves=0, min_child_weight=1, missing=nan,
             monotone_constraints='()', n_estimators=100, n_jobs=0,
             num_parallel_tree=1, predictor='auto', random_state=0, ...)

In [46]:
pred = xgb.predict(benz_test_df)

In [47]:
pred

array([ 73.71088 ,  99.586426,  84.98918 , ..., 103.67071 , 116.15893 ,
        94.410194], dtype=float32)

In [50]:
benz_test_result = pd.DataFrame(pred, columns=['y'])

In [52]:
benz_test_result

y
0      73.710876
1      99.586426
2      84.989182
3      80.629761
4     101.920486
...          ...
4204  106.329224
4205  108.064598
4206  103.670708
4207  116.158928
4208   94.410194

[4209 rows x 1 columns]